name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Rust CI (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, 1.70.0]
    continue-on-error: ${{ matrix.toolchain != 'stable' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Cache cargo
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo fmt --check
        run: cargo fmt --all --check

      - name: cargo clippy -D warnings
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: cargo build --locked
        run: cargo build --locked --all-targets

      - name: cargo test --locked
        run: cargo test --locked --all-features -- --nocapture
