name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  BINARY_NAME: codex-tools-mcp
jobs:
  build:
    name: Build ${{ matrix.os_name }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            os_name: linux
            arch: amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            os_name: linux
            arch: arm64
            use_cross: true
          - os: macos-13
            target: x86_64-apple-darwin
            os_name: darwin
            arch: amd64
          - os: macos-14
            target: aarch64-apple-darwin
            os_name: darwin
            arch: arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            os_name: windows
            arch: amd64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Install cross (for linux/arm64)
        if: ${{ matrix.use_cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build (release)
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ matrix.use_cross || '' }}" == "true" ]]; then
            cross build --locked --release --target ${{ matrix.target }}
          else
            cargo build --locked --release --target ${{ matrix.target }}
          fi
      - name: Package artifact (non-Windows)
        if: ${{ matrix.os_name != 'windows' }}
        shell: bash
        run: |
          set -euo pipefail
          NAME="${BINARY_NAME}"
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#v}"
          OS="${{ matrix.os_name }}"
          ARCH="${{ matrix.arch }}"
          BIN="target/${{ matrix.target }}/release/${NAME}"
          STAGE="dist/${NAME}_${VERSION}_${OS}_${ARCH}"
          mkdir -p "$STAGE"
          cp "$BIN" "$STAGE/"
          tar -C "dist" -czf "${STAGE}.tar.gz" "$(basename "$STAGE")"
      - name: Package artifact (Windows)
        if: ${{ matrix.os_name == 'windows' }}
        shell: pwsh
        run: |
          $Name = "$env:BINARY_NAME"
          $Tag = "${{ github.event.release.tag_name }}"
          $Version = $Tag.TrimStart('v')
          $OS = "${{ matrix.os_name }}"
          $Arch = "${{ matrix.arch }}"
          $Bin = "target/${{ matrix.target }}/release/$Name.exe"
          $Stage = "dist/${Name}_${Version}_${OS}_${Arch}"
          New-Item -ItemType Directory -Force -Path $Stage | Out-Null
          Copy-Item $Bin $Stage/
          Compress-Archive -Path "$Stage/*" -DestinationPath "$Stage.zip"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os_name }}-${{ matrix.arch }}
          path: |
            dist/*.tar.gz
            dist/*.zip
          if-no-files-found: error
          retention-days: 7
  publish:
    name: Attach assets to Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Generate SHA256 checksums
        shell: bash
        run: |
          set -euo pipefail
          cd dist
          shopt -s nullglob
          files=( *.tar.gz *.zip )
          if [ ${#files[@]} -eq 0 ]; then
            echo "No packaged artifacts found" >&2
            exit 1
          fi
          sha256sum "${files[@]}" > SHA256SUMS.txt
          cat SHA256SUMS.txt
      - name: Upload assets to existing release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          generate_release_notes: false
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
