name: Release Please
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release-as:
        description: 'Force a release version (e.g., 0.2.0) [optional]'
        required: false
        type: string
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: rust
          package-name: codex-tools-mcp
          bump-minor-pre-major: true
          release-as: ${{ inputs.release-as }}
