name: Release Please
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release-as:
        description: 'Force a release version (e.g., 0.2.0) [optional]'
        required: false
        type: string
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check release token
        if: ${{ !secrets.RELEASE_PLEASE_TOKEN }}
        run: |
          echo "Missing required secret RELEASE_PLEASE_TOKEN (fine-grained PAT with contents:rw, pull_requests:rw)." >&2
          exit 1
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: rust
          package-name: codex-tools-mcp
          bump-minor-pre-major: true
          release-as: ${{ inputs.release-as }}
